---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moviefun-pks-pvc
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # request 1 Gig of storage
      storage: 1Gi