---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: moviefun-pks-claim
  annotations:
    # specifically request the thin storage class
    volume.beta.kubernetes.io/storage-class: thin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # request 1 Gig of storage
      storage: 1Gi
