---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: moviefun-pks
  template:
    metadata:
      labels:
        app: moviefun-pks
    spec:
      containers:
        - name: moviefun-pks
          image: pivotaleducation/moviefun-pks:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 800m
