---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviefun-pks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moviefun-pks
  template:
    metadata:
      labels:
        app: moviefun-pks
    spec:
      volumes:
        - name: album-covers-disk
          persistentVolumeClaim:
            claimName: moviefun-pks-claim
      containers:
        - name: moviefun-pks
          image: pivotaleducation/moviefun-pks:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 800m
          volumeMounts:
            - mountPath: "/var/albumCovers"
              name: album-covers-disk
